version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=lms-db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=P@ssw0rd
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/lms-db
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: P@ssw0rd
    links:
      - db
    volumes:
      - ./:/src
volumes:
  db:
    driver: local